# Generated by Django 5.2.6 on 2025-09-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_menuitem_image_url_menuitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='cuisine_type',
            new_name='cuisine',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='deliveryFee',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='deliveryTime',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='distance',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='offer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
