# Generated by Django 5.2.6 on 2025-09-29 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_cuisine_type_restaurant_cuisine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='cuisine',
            new_name='cuisine_type',
        ),
    ]
