# Generated by Django 5.2.6 on 2025-09-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_rename_cuisine_restaurant_cuisine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
