# Generated by Django 5.2.6 on 2025-09-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menuitem_image_alter_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Pizza', 'Pizza'), ('Pasta', 'Pasta'), ('Salads', 'Salads'), ('Drinks', 'Drinks'), ('Desserts', 'Desserts')], default='Popular', max_length=50),
        ),
    ]
